export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const END_AJAX_CALL = "END_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";
export const LOAD_LIST_OF_GTIN_NOT_RECEIVED_SUCCESS =
  "LOAD_LIST_OF_GTIN_NOT_RECEIVED_SUCCESS";
export const LOAD_SERVICE_REQUEST_CURRENT_WEEKS =
  "LOAD_SERVICE_REQUEST_CURRENT_WEEKS";
