export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const END_AJAX_CALL = "END_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";
export const LOAD_LIST_OF_GTIN_NOT_RECEIVED = "LOAD_LIST_OF_GTIN_NOT_RECEIVED";
export const LOAD_CURRENT_WEEKS = "LOAD_CURRENT_WEEKS";
export const LOAD_DEFAULT_WEEK = "LOAD_DEFAULT_WEEK";
